### ISSUE TITLE
Removing paragraph indentation?

### ISSUE THREAD

**Issue by barryphayes** [PierreSenellart/erc-latex-template#1]
Does anyone know how to remove paragraph indentation either selectively, or across the entire B1 and B2 documents? Typical LaTeX commands like "\noindent" are not recognised.

**Comment by PierreSenellart** [comment]
The template does not change in any way standard LaTeX paragraph indentation.

You can use `\noindent` to selectively not indent a paragraph (I have just verified this is indeed working) or `\setlength{\parindent}{0pt}` (for example added to the `erc-common.tex` file) to remove indentation in the entire document altogether (see also the `parskip` package if you want to add spacing between paragraphs in lieu of indenting).
