### ISSUE TITLE
Space before and after section and subsection titles in B2

### ISSUE THREAD

**Issue by irenescha** [PierreSenellart/erc-latex-template#5]
Hi! 
Many thanks for the template. I would like to reduce the space before and after the sections and subsections titles of part B2, but I cannot find where to do so...can you help me with it?
Many thanks!
I.

**Comment by PierreSenellart** [comment]
The template is based on Koma Script's `scrartcl` document class, so anything that works with that class should do the trick. See the discussion on https://tex.stackexchange.com/questions/223508/adjusting-spacing-around-section-subsection-titles-with-koma-script for example.
