### ISSUE TITLE
Add "Section a:"

### ISSUE THREAD

**Issue by Shirin60** [PierreSenellart/erc-latex-template#8]
Is there a way to change the section numbering to include the word "Section"? For example "Section a: XXX" Instead of "a XXX". Thank you for saving us enormous amount of time by providing Latex template.

**Comment by PierreSenellart** [comment]
The template uses a standard KOMA Script document class, so you can use the KOMA Script features to customize its appearance. Here, to change how Section headers are displayed, you can use something like:
  \renewcommand*\sectionformat{Section~\thesection:\enskip}


See the documentation of \sectionformat in
https://mirrors.ircam.fr/pub/CTAN/macros/latex/contrib/koma-script/doc/scrguien.pdf
